services:
  api:
    build:
      context: ..
      dockerfile: Dockerfile
      target: development
    container_name: dermofarm-api-prod
    restart: unless-stopped
    ports:
      - "${PORT:-3000}:${PORT:-3000}"
    env_file:
      - .env.prd
    environment:
      - NODE_ENV=development
      - IS_DOCKER=true
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:${PORT:-3000}/api"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
